

dmarket_public_key = "341c7893bd5d1cf05150a38fcabd4008f01e9edb473e7c91ea5199ce088b0b8b"
dmarket_secret_key = "4016059fb0b3b6ba29c31cb06a224c5951312a7b0a59e964faf558ce0c1e65af341c7893bd5d1cf05150a38fcabd4008f01e9edb473e7c91ea5199ce088b0b8b"
authorization="eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlOTNkMWQxZC0wMjk1LTRiNWItOTA2YS1hYWJmZDhkZDZjM2EiLCJleHAiOjE3MzIwODE4MjIsImlhdCI6MTcyOTQ4OTgyMiwic2lkIjoiYjJmZjBiODAtMTU4Ni00Y2FkLWI4OGYtMzIwZDIxZmFkZDFkIiwidHlwIjoiYWNjZXNzIiwiaWQiOiI0MWU0Y2RlZC1hMDcxLTRiMDUtODRjYS1lYzM2OWEzZjYyZjUiLCJwdmQiOiJyZWd1bGFyIiwicHJ0IjoiMjQxMCIsImF0dHJpYnV0ZXMiOnsic2FnYV93YWxsZXRfYWRkcmVzcyI6IjB4Qzc5ZmUzOGMzQjgzMmQ4NTZkMkYxRWZBMEZjMDBFRTMxOEE5MzY2NCIsImFjY291bnRfaWQiOiI4NmFmZDFmZi0wNWU4LTQ3MzktOTM2ZC03YjY1ZTA5ZDc4NWUiLCJ3YWxsZXRfaWQiOiJmODUxMzhiNzQ1YWI0YjJjYWM1NjdlMWYwNWY3ZWY0ZmU0MmMxNTNjMmQxODQ0MzViODY5OTc4M2QwOWM5ODE1In19.PMWgHARt63_aDp5ntYF6lkn3ffb-pG8rQTngRRhO9jP54Fm_K9NvNuKk_7JbBEckdZRy8dnSg3gqlIvFgk49eA"

# 初始化文件夹
data_local="data_local"
data_local_excel=data_local+"/excel"
data_local_analysis=data_local+"/analysis"

#文件路径-源文件
cs_product_all_name="data/cs_product_all_name.txt"


#文件路径-查询数据
skin_86_product_all=data_local_analysis+"/skin_86_product_all.txt" # buff的源数据
skin_86_product_all_buy=data_local_analysis+"/skin_86_product_all_buy.txt" # buff的源数据
buff_filter_file=data_local_analysis+"/skin_86_filter_file.txt" # buff的源数据
filter_data_not_buy="data/filter_data_not_buy.txt" # 过滤购买的数据


# 查询 三羊平台的数据实时分析导购
skin_86_product_all_buff=data_local_analysis+"/skin_86_product_all_buff.txt" # buff的源数据
skin_86_product_all_yp=data_local_analysis+"/skin_86_product_all_yp.txt" # buff的源数据
skin_86_product_all_igxe=data_local_analysis+"/skin_86_product_all_igxe.txt" # buff的源数据
skin_86_product_all_steam=data_local_analysis+"/skin_86_product_all_steam.txt" # buff的源数据
csgo_db_deal=data_local_analysis+"/csgo_db_deal.txt" # 实时成交数据



# 保存 三羊平台的数据到数据库 每天定时查询
skin_86_product_all_buff_mysql=data_local_analysis+"/skin_86_product_all_buff_mysql.txt" # buff的源数据
skin_86_product_all_yp_mysql=data_local_analysis+"/skin_86_product_all_yp_mysql.txt" # buff的源数据
skin_86_product_all_igxe_mysql=data_local_analysis+"/skin_86_product_all_igxe_mysql.txt" # buff的源数据
skin_86_product_all_steam_mysql=data_local_analysis+"/skin_86_product_all_steam_mysql.txt" # buff的源数据
csgo_db_deal_mysql=data_local_analysis+"/csgo_db_deal_mysql.txt" # 实时成交数据

# 下载挂刀网站的数据，分析导购
priority_archive="priority_archive.json"



